
#' Export options
#' @export
#' @return a string (character of length 1) representing the .ini file
generate_export_opt_ini = function(models=c("all", "best fit"), line_delim=c("DOS/Windows", "unix"),
                                   na=c("space", "period", "na"), field_delim=c("tab", "comma", "semi-colon"),
                                   by_var_format=c("numeric", "quoted labels", "unquoted labels"),
                                   export_type=c("table", "text"), remove_jp_flags=TRUE,
                                   remove_best_fit_flags=FALSE, output_bygroup_headers=TRUE,
                                   all_models_in_same_column=FALSE, include_jp_estimates=FALSE,
                                   include_apcs=TRUE, x_precision=9, y_precision=9, model_precision=3,
                                   estimated_joinpoint_precision=3, regression_coefficients_precision=3,
                                   covariance_matrix_precision=3, correlation_matrix_precision=3,
                                   apc_precision=3,aapc_precision=3, aapc_segemnt_ranges_precision=3,
                                   pvalue_precision=3,
                                   aapc_full_range=FALSE,
                                   aapc_start_range1 = NULL, aapc_end_range1 = NULL,
                                   aapc_start_range2 = NULL, aapc_end_range2 = NULL,
                                   aapc_start_range3 = NULL, aapc_end_range3 = NULL,
                                   aapc_last_obs=FALSE,
                                   export_bad_cohorts=TRUE, export_report=TRUE, export_data=TRUE,
                                   export_apc=TRUE, export_aapc=TRUE, export_ftest=TRUE,
                                   export_pairwise=TRUE, export_jump_cr=TRUE
){

  txt = glue(.sep="\n", .null=NULL,
             "[Export Options]",
             f("Models", match.arg(models), missing(models)),
             f("Line delimiter", match.arg(line_delim), missing(line_delim)),
             f("Missing character", match.arg(na), missing(na)),
             f("Field delimiter", match.arg(field_delim), missing(field_delim)),
             f("By-var format", match.arg(by_var_format), missing(by_var_format)),
             f("Export type", match.arg(export_type), missing(export_type)),
             f("Remove JP flags", remove_jp_flags, missing(remove_jp_flags)),
             f("Remove best fit flags", remove_best_fit_flags, missing(remove_best_fit_flags)),
             f("Output by-group headers", output_bygroup_headers, missing(output_bygroup_headers)),
             f("All models in same column", all_models_in_same_column, missing(all_models_in_same_column)),
             f("Include JP estimates", include_jp_estimates, missing(include_jp_estimates)),
             f("Include apcs in data export", include_apcs, missing(include_apcs)),
             f("X Values Precision", x_precision, missing(x_precision)),
             f("Y Values Precision", y_precision, missing(y_precision)),
             f("Model Statistics Precision", model_precision, missing(model_precision)),
             f("Estimated Joinpoints Precision", estimated_joinpoint_precision,
               missing(estimated_joinpoint_precision)),
             f("Regression Coefficients Precision", regression_coefficients_precision,
               missing(regression_coefficients_precision)),
             f("Covariance Matrix Precision", covariance_matrix_precision, missing(covariance_matrix_precision)),
             f("Correlation Matrix Precision", correlation_matrix_precision, missing(correlation_matrix_precision)),
             f("APC Precision", apc_precision, missing(apc_precision)),
             f("AAPC Precision", aapc_precision, missing(aapc_precision)),
             f("AAPC Segment Ranges Precision", aapc_segemnt_ranges_precision, missing(aapc_segemnt_ranges_precision)),
             f("P-Value Precision", pvalue_precision, missing(pvalue_precision)),
             f("AAPC Full Range", aapc_full_range, missing(aapc_full_range)),
             f("AAPC Start Range1", aapc_start_range1, missing(aapc_start_range1)),
             f("AAPC End Range1", aapc_end_range1, missing(aapc_end_range1)),
             f("AAPC Start Range2", aapc_start_range2, missing(aapc_start_range2)),
             f("AAPC End Range2", aapc_end_range2, missing(aapc_end_range2)),
             f("AAPC Start Range3", aapc_start_range3, missing(aapc_start_range3)),
             f("AAPC End Range3", aapc_end_range3, missing(aapc_end_range3)),
             f("AAPC Last Obs", aapc_last_obs, missing(aapc_last_obs)),
             f("Export Bad Cohorts", export_bad_cohorts, missing(export_bad_cohorts)),
             f("Export Report", export_report, missing(export_report)),
             f("Export data", export_data, missing(export_data)),
             f("Export apc", export_apc, missing(export_apc)),
             f("Export aapc", export_aapc, missing(export_aapc)),
             f("Export ftest", export_ftest, missing(export_ftest)),
             f("Export pairwise", export_pairwise, missing(export_pairwise)),
             f("Export jump_cr", export_jump_cr, missing(export_jump_cr)),
  )
  txt
}
